/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gamepad4j_desktop_GamepadJniWrapper */

#ifndef _Included_org_gamepad4j_desktop_GamepadJniWrapper
#define _Included_org_gamepad4j_desktop_GamepadJniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gamepad4j_desktop_GamepadJniWrapper
 * Method:    natInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gamepad4j_desktop_GamepadJniWrapper_natInit
  (JNIEnv *, jobject);

/*
 * Class:     org_gamepad4j_desktop_GamepadJniWrapper
 * Method:    natRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gamepad4j_desktop_GamepadJniWrapper_natRelease
  (JNIEnv *, jobject);

/*
 * Class:     org_gamepad4j_desktop_GamepadJniWrapper
 * Method:    natGetNumberOfPads
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gamepad4j_desktop_GamepadJniWrapper_natGetNumberOfPads
  (JNIEnv *, jobject);

/*
 * Class:     org_gamepad4j_desktop_GamepadJniWrapper
 * Method:    natDetectPads
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gamepad4j_desktop_GamepadJniWrapper_natDetectPads
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
